apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-aggregator-config
  namespace: monitoring
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/aggregator.log
      fields:
        app: aggregator
        environment: monitoring
        app_service: metrics-aggregator
      fields_under_root: true
      
    output.logstash:
      hosts: ["logstash:5044"]

    queue.mem:
      events: 2048
      flush.min_events: 200
      flush.timeout: 5s

    logging.level: info
    logging.to_stderr: true