apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-aggregator-config
  namespace: monitoring
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/aggregator.log
      fields:
        app: aggregator
        environment: monitoring
        service: metrics-aggregator
      fields_under_root: true
      multiline.pattern: '^\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}'
      multiline.negate: true
      multiline.match: after
      json.keys_under_root: false
      json.add_error_key: true
      
    processors:
    - add_host_metadata:
        when.not.contains.tags: forwarded
    - add_kubernetes_metadata:
        host: ${NODE_NAME}
        matchers:
        - logs_path:
            logs_path: "/var/log/containers/"
    - timestamp:
        field: '@timestamp'
        layouts:
          - '2006/01/02 15:04:05'
        test:
          - '2025/08/11 17:19:16'
          
    output.logstash:
      hosts: ["logstash:5044"]
      
    logging.level: info
    logging.to_files: false
    logging.to_stderr: true