apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.7.0
        env:
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: "5601"
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-lb:9200"
        - name: XPACK_SECURITY_ENABLED
          value: "false"
        - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
          value: "something_at_least_32_characters_long_for_encryption"
        - name: XPACK_MONITORING_ENABLED
          value: "false"
        - name: NODE_OPTIONS
          value: "--max-old-space-size=1536"
        ports:
        - containerPort: 5601
          name: http
        resources:
          requests:
            cpu: "300m"
            memory: "768Mi"
          limits:
            cpu: "1000m"
            memory: "1.5Gi"
        readinessProbe:
          httpGet:
            path: /api/status
            port: 5601
          initialDelaySeconds: 90
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /api/status
            port: 5601
          initialDelaySeconds: 120
          periodSeconds: 30
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: monitoring
spec:
  selector:
    app: kibana
  ports:
  - port: 5601
    targetPort: 5601