apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: monitoring
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    
    output {
      elasticsearch {
        hosts => ["http://192.168.0.45:9200"]
        index => "aggregator-logs"
      }
      
      stdout {
        codec => rubydebug
      }
    }