apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.11.0
        env:
        # CRITICAL: Disable monitoring to reduce ES connection pressure
        - name: XPACK_MONITORING_ENABLED
          value: "false"
        - name: PIPELINE_WORKERS
          value: "1"
        - name: LOG_LEVEL
          value: "info"
        ports:
        - containerPort: 5044
          name: beats
        volumeMounts:
        - name: logstash-pipeline
          mountPath: /usr/share/logstash/pipeline/
        resources:
          requests:
            cpu: "300m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        # Health checks
        readinessProbe:
          tcpSocket:
            port: 5044
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5044
          initialDelaySeconds: 90
          periodSeconds: 30
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
      volumes:
      - name: logstash-pipeline
        configMap:
          name: logstash-pipeline
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: monitoring
spec:
  selector:
    app: logstash
  ports:
  - port: 5044
    targetPort: 5044
    name: beats