apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: monitoring
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    
    filter {
      if [message] =~ /Sending JSON to VictoriaMetrics:/ {
        mutate {
          add_field => { "contains_json" => "true" }
          add_tag => [ "has_victoria_metrics_json" ]
        }
        
        ruby {
          code => '
            msg = event.get("message")
            if msg.include?("VictoriaMetrics: ")
              json_part = msg.split("VictoriaMetrics: ", 2)[1]
              event.set("json_payload", json_part)
            end
          '
        }
        
        if [json_payload] {
          json {
            source => "json_payload"
            target => "victoria_data"
          }
          
          if [victoria_data][metric][__name__] {
            mutate {
              add_field => { 
                "metric_name" => "%{[victoria_data][metric][__name__]}" 
              }
            }
          }
          
          if [victoria_data][values] and [victoria_data][values][0] {
            mutate {
              add_field => { "metric_value" => "%{[victoria_data][values][0]}" }
              convert => { "metric_value" => "float" }
            }
          }
        }
      }
      
      if [message] =~ /Successfully processed and sent metrics/ {
        mutate {
          add_tag => [ "metrics_success" ]
        }
      }
    }
    
    output {
      elasticsearch {
        # ✅ CORRECTED: Use load balancer endpoint
        hosts => ["http://elasticsearch-lb:9200"]
        index => "aggregator-logs-write"

        timeout => 60
        pool_max => 20
        pool_max_per_route => 10
        
        # Template management
        manage_template => false
      }
      
      stdout {
        codec => rubydebug
      }
    }