apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: monitoring
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    
    filter {
      # Add timestamp parsing for better log handling
      if [kubernetes][container][name] == "agent" {
        grok {
          match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{GREEDYDATA:log_message}" }
        }
        mutate {
          add_tag => [ "agent-logs" ]
        }
      }
      
      if [kubernetes][container][name] == "aggregator" {
        grok {
          match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{GREEDYDATA:log_message}" }
        }
        mutate {
          add_tag => [ "aggregator-logs" ]
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://192.168.0.45:9200"]
        index => "monitoring-logs-%{+YYYY.MM.dd}"
        # Disable template management to reduce ES load
        manage_template => false
      }
      
      # Add stdout for debugging
      stdout {
        codec => rubydebug
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.11.0
        env:
        # CRITICAL: Disable monitoring to reduce ES connection pressure
        - name: XPACK_MONITORING_ENABLED
          value: "false"
        - name: PIPELINE_WORKERS
          value: "1"
        - name: LOG_LEVEL
          value: "info"
        ports:
        - containerPort: 5044
          name: beats
        volumeMounts:
        - name: logstash-pipeline
          mountPath: /usr/share/logstash/pipeline/
        resources:
          requests:
            cpu: "300m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        # Health checks
        readinessProbe:
          tcpSocket:
            port: 5044
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5044
          initialDelaySeconds: 90
          periodSeconds: 30
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
      volumes:
      - name: logstash-pipeline
        configMap:
          name: logstash-pipeline
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: monitoring
spec:
  selector:
    app: logstash
  ports:
  - port: 5044
    targetPort: 5044
    name: beats