apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "kafka.name" . }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.service.clientPort }}
    name: client
  - port: {{ .Values.service.brokerPort }}
    name: broker
  - port: {{ .Values.service.controllerPort }}
    name: controller
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "kafka.name" . }}