apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.clientPort }}
      name: client
    - port: {{ .Values.service.brokerPort }}
      name: broker
    - port: {{ .Values.service.controllerPort }}
      name: controller
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}