apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: monitoring
spec:
  clusterIP: None  # This makes it headless
  ports:
  - port: 9092
    name: client
  - port: 9093
    name: broker
  - port: 9094
    name: controller
  selector:
    app: kafka  # Must match your StatefulSet's pod labels