apiVersion: v1
kind: Service
metadata:
  name: kafka  # Use simple fixed name to match StatefulSet
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.clientPort }}
      name: client
    - port: {{ .Values.service.brokerPort }}
      name: broker
    - port: {{ .Values.service.controllerPort }}
      name: controller
  selector:
    app: kafka  # Must match StatefulSet's pod labels