apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: KAFKA_BROKERS
              value: "{{ .Values.env.kafkaBrokers }}"
            - name: KAFKA_TOPIC
              value: "{{ .Values.env.kafkaTopic }}"
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
