apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-0
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath-delayed-binding
  hostPath:
    path: /tmp/kafka-pv/kafka-data-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-1
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath-delayed-binding
  hostPath:
    path: /tmp/kafka-pv/kafka-data-1