apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kafka-1
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath-delayed-binding