apiVersion: v1
kind: ServiceAccount
metadata:
  name: alerting
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alerting-pod-watcher
rules:
- apiGroups: [""]
  resources: ["pods", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alerting-pod-watcher-binding
subjects:
- kind: ServiceAccount
  name: alerting
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: alerting-pod-watcher
  apiGroup: rbac.authorization.k8s.io