apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-admin-binding
  namespace: argocd
subjects:
- kind: User
  name: alex  # Replace with your username or service account
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: argocd-admin  # This grants admin privileges
  apiGroup: rbac.authorization.k8s.io
