http: 
  port: 8099
db:
  host: localhost
  port: 5433
  database: alerting 
  user: alerting_service
  password: alerting_secure_password123
slack:
  enabled: true
  channels: 
        default: "#all-gomon-monitoring"
        critical: "#alert-critical"