name: Update Agent K8s YAML

on:
  repository_dispatch:
    types: [agent_image_pushed]

jobs:
  update-agent-yml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract image info
        run: |
          echo "Image: ${{ github.event.client_payload.image }}"
          echo "Tag: ${{ github.event.client_payload.tag }}"

      - name: Update agent-deployment.yaml
        run: |
          FILE=k8s/agent-deployment.yaml
          IMAGE="${{ github.event.client_payload.image }}:${{ github.event.client_payload.tag }}"
          echo "Updating $FILE to use image $IMAGE"
          sed -i "s|image:.*ragazzo271985/agent.*|image: $IMAGE|" $FILE

      - name: Commit and push changes
        run: |
          git config --global user.email "alexander.peshkov27@gmail.com"
          git config --global user.name "Alexander Peshkov"
          git add k8s/agent-deployment.yaml
          git commit -m "Update agent image to $IMAGE"
          git push
