apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent
  namespace: monitoring
spec:
  project: default
  source:
    repoURL: 'https://github.com/0xAxPx/gomon.git'
    targetRevision: main
    path: charts/agent-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true