apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/0xAxPx/gomon.git
    targetRevision: HEAD
    path: charts/gomon-stack
    helm:
      values: |
        agent:
          image:
            tag: "20250503-f5ef22a"
        kafka:
          replicas: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true